apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: cert-manager
  namespace: cert-manager

resources:
  - selfsigned-issuer.yaml
  - certificate.yaml

commonLabels:
  app.kubernetes.io/name: cert-manager
  app.kubernetes.io/part-of: tls-management 