apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-app-of-apps-root
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/davidagustin/authpractice.git'
    targetRevision: main
    path: argocd/infra
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true 