apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: authpractice
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/davidagustin/authpractice.git'
    targetRevision: main
    path: helm
    helm:
      valueFiles:
        - values.yaml
      # Use chart version instead of latest tag
      values: |
        image:


          tag: "0.1.3"

          tag: "0.1.2"


          tag: "0.1.3"

  destination:
    server: https://kubernetes.default.svc
    namespace: authpractice
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true 