apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: authpractice-develop
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/YOUR_GITHUB_USERNAME/YOUR_REPO_NAME.git'
    targetRevision: develop
    path: helm
    helm:
      valueFiles:
        - values-develop.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: authpractice-develop
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true 