# Production environment values
# Extends base values.yaml with production-specific overrides

replicaCount: 2

image:
  repository: authpractice
  pullPolicy: IfNotPresent
  tag: "0.1.8"

service:
  type: NodePort
  port: 3000
  nodePort: 32002

ingress:
  enabled: false

# Production-specific resource limits
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

# Production-specific probe settings
livenessProbe:
  httpGet:
    path: /
    port: http
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3

readinessProbe:
  httpGet:
    path: /
    port: http
  initialDelaySeconds: 5
  periodSeconds: 5
  timeoutSeconds: 3
  failureThreshold: 3

# Production labels and annotations
podLabels:
  environment: production
  tier: frontend

podAnnotations:
  environment: production
  deployment-type: production 